// Telegram bot texts for hosts (ru / ky / en). Kyrgyz — draft for proofreading.

import type { Lang } from '../../../src/domain/types';

export const BOT = {
  ru: {
    welcome: 'Это бот Voyz Booking. Сюда приходят новые брони и оплаты — подтверждайте прямо из чата.',
    loginOk: 'Готово! Вернитесь в приложение Voyz — вход выполнен.',
    loginExpired: 'Код входа устарел. Нажмите «Войти через Telegram» в приложении ещё раз.',
    newBooking: 'Новая бронь',
    guestPaid: 'Гость сообщил об оплате — проверьте счёт',
    guestCancelled: 'Гость отменил бронь',
    holdExpired: 'Бронь снята: предоплата не пришла вовремя',
    icalConflict: 'Внимание: двойная продажа! Площадка заняла даты, на которые уже есть бронь',
    icalGone: 'Бронь пропала из календаря площадки — возможно, гость отменил её там. Проверьте в экстранете и отмените бронь в Voyz, чтобы Aynes не считал эту выручку',
    nights: (n: number) => `${n} ноч.`,
    guests: (n: number) => `${n} гост.`,
    total: 'Сумма',
    deposit: (x: string, until: string) => `Предоплата ${x}${until ? ` до ${until}` : ''}`,
    confirm: '✅ Подтвердить',
    decline: '✖️ Отклонить',
    received: '💰 Деньги пришли',
    open: 'Открыть в приложении',
    done: { confirmed: '✅ Подтверждена', cancelled: '✖️ Отклонена', deposit: '💰 Предоплата отмечена, бронь подтверждена' },
    notYours: 'Эта бронь не ваша или уже изменена',
    summary: (name: string) => `Доброе утро! «${name}» сегодня`,
    arrivals: 'Заезжают',
    departures: 'Выезжают',
    pending: (n: number) => `Ждут подтверждения: ${n}`,
    nothing: 'Заездов и выездов нет',
  },
  ky: {
    welcome: 'Бул Voyz Booking боту. Бул жерге жаңы брондоолор жана төлөмдөр келет — чаттан эле ырастаңыз.',
    loginOk: 'Даяр! Voyz тиркемесине кайтыңыз — кирүү аткарылды.',
    loginExpired: 'Кирүү коду эскирди. Тиркемеде «Telegram аркылуу кирүү» баскычын кайра басыңыз.',
    newBooking: 'Жаңы брондоо',
    guestPaid: 'Конок төлөдүм деп билдирди — эсепти текшериңиз',
    guestCancelled: 'Конок брондоону жокко чыгарды',
    holdExpired: 'Брондоо алынды: алдын ала төлөм убагында келген жок',
    icalConflict: 'Көңүл буруңуз: эки жолу сатуу! Аянтча брондоосу бар күндөрдү ээледи',
    icalGone: 'Брондоо аянтчанын календарынан жоголду — конок аны ал жакта жокко чыгарган болушу мүмкүн. Экстранеттен текшерип, Aynes бул кирешени эсептебеши үчүн Voyz’до брондоону жокко чыгарыңыз',
    nights: (n: number) => `${n} түн`,
    guests: (n: number) => `${n} конок`,
    total: 'Сумма',
    deposit: (x: string, until: string) => `Алдын ала төлөм ${x}${until ? `, ${until} чейин` : ''}`,
    confirm: '✅ Ырастоо',
    decline: '✖️ Баш тартуу',
    received: '💰 Акча келди',
    open: 'Тиркемеден ачуу',
    done: { confirmed: '✅ Ырасталды', cancelled: '✖️ Баш тартылды', deposit: '💰 Алдын ала төлөм белгиленди, брондоо ырасталды' },
    notYours: 'Бул брондоо сиздики эмес же өзгөртүлгөн',
    summary: (name: string) => `Кутман таң! «${name}» бүгүн`,
    arrivals: 'Келишет',
    departures: 'Кетишет',
    pending: (n: number) => `Ырастоону күтүүдө: ${n}`,
    nothing: 'Келүү жана кетүү жок',
  },
  en: {
    welcome: 'This is the Voyz Booking bot. New bookings and payments arrive here — confirm them right from the chat.',
    loginOk: 'Done! Go back to the Voyz app — you are signed in.',
    loginExpired: 'The sign-in code has expired. Tap “Sign in with Telegram” in the app again.',
    newBooking: 'New booking',
    guestPaid: 'The guest reported a payment — check your account',
    guestCancelled: 'The guest cancelled the booking',
    holdExpired: 'Booking released: the deposit did not arrive in time',
    icalConflict: 'Warning: double booking! An OTA blocked dates that already have a booking',
    icalGone: 'A booking has left the OTA calendar — the guest may have cancelled it there. Check the extranet and cancel the booking in Voyz so Aynes does not count this revenue',
    nights: (n: number) => `${n} night${n === 1 ? '' : 's'}`,
    guests: (n: number) => `${n} guest${n === 1 ? '' : 's'}`,
    total: 'Total',
    deposit: (x: string, until: string) => `Deposit ${x}${until ? ` by ${until}` : ''}`,
    confirm: '✅ Confirm',
    decline: '✖️ Decline',
    received: '💰 Money received',
    open: 'Open in the app',
    done: { confirmed: '✅ Confirmed', cancelled: '✖️ Declined', deposit: '💰 Deposit recorded, booking confirmed' },
    notYours: 'This booking is not yours or has already changed',
    summary: (name: string) => `Good morning! “${name}” today`,
    arrivals: 'Arriving',
    departures: 'Leaving',
    pending: (n: number) => `Awaiting confirmation: ${n}`,
    nothing: 'No arrivals or departures',
  },
} satisfies Record<Lang, unknown>;

export function botCopy(lang: string) {
  return BOT[(lang in BOT ? lang : 'ru') as Lang];
}

// ---------- Guests (no account: they follow one booking after tapping the link) ----------

export type GuestEvent = 'linked' | 'confirmed' | 'declined' | 'expired' | 'extended' | 'deposit' | 'reminder';

const GUEST = {
  ru: {
    event: {
      linked: '🔔 Готово! Сюда придут новости о вашей брони.',
      confirmed: '✅ Хозяин подтвердил бронь',
      declined: '✖️ Хозяин отменил бронь',
      expired: '⌛ Бронь снята: предоплата не поступила вовремя',
      extended: '⏳ Хозяин продлил срок оплаты',
      deposit: '💰 Хозяин получил предоплату',
      reminder: '⏰ Бронь скоро снимется — осталось внести предоплату',
    },
    status: {
      pending: 'Статус: ждёт подтверждения хозяина',
      confirmed: 'Статус: подтверждена',
      checked_in: 'Статус: вы заселились',
      checked_out: 'Статус: выезд',
      cancelled: 'Статус: отменена',
      no_show: 'Статус: незаезд',
    },
    booking: (id: string) => `Бронь ${id}`,
    times: (inTime: string, outTime: string) => `Заезд с ${inTime}, выезд до ${outTime}`,
    due: (x: string, until: string) => `Предоплата ${x}${until ? ` — оплатите до ${until}` : ''}`,
    payTo: (recipient: string, details: string) => `Получатель: ${[recipient, details].filter(Boolean).join(' · ')}`,
    comment: (id: string) => `Комментарий к переводу: ${id}`,
    open: 'Открыть бронь',
    linkExpired: 'Ссылка устарела. Откройте бронь в приложении и нажмите «Следить за бронью в Telegram» ещё раз.',
  },
  ky: {
    event: {
      linked: '🔔 Даяр! Брондооңуз тууралуу жаңылыктар ушул жерге келет.',
      confirmed: '✅ Ээси брондоону ырастады',
      declined: '✖️ Ээси брондоону жокко чыгарды',
      expired: '⌛ Брондоо алынды: алдын ала төлөм убагында келген жок',
      extended: '⏳ Ээси төлөө мөөнөтүн узартты',
      deposit: '💰 Ээси алдын ала төлөмдү алды',
      reminder: '⏰ Брондоо жакында алынат — алдын ала төлөм калды',
    },
    status: {
      pending: 'Абалы: ээсинин ырастоосун күтүүдө',
      confirmed: 'Абалы: ырасталды',
      checked_in: 'Абалы: жайгаштыңыз',
      checked_out: 'Абалы: чыгуу',
      cancelled: 'Абалы: жокко чыгарылды',
      no_show: 'Абалы: келген жок',
    },
    booking: (id: string) => `Брондоо ${id}`,
    times: (inTime: string, outTime: string) => `Келүү ${inTime} баштап, кетүү ${outTime} чейин`,
    due: (x: string, until: string) => `Алдын ала төлөм ${x}${until ? ` — ${until} чейин төлөңүз` : ''}`,
    payTo: (recipient: string, details: string) => `Алуучу: ${[recipient, details].filter(Boolean).join(' · ')}`,
    comment: (id: string) => `Которуудагы комментарий: ${id}`,
    open: 'Брондоону ачуу',
    linkExpired: 'Шилтеме эскирди. Тиркемеден брондоону ачып, «Брондоону Telegram аркылуу көзөмөлдөө» баскычын кайра басыңыз.',
  },
  en: {
    event: {
      linked: '🔔 Done! News about your booking will arrive here.',
      confirmed: '✅ The host confirmed your booking',
      declined: '✖️ The host cancelled the booking',
      expired: '⌛ Booking released: the deposit did not arrive in time',
      extended: '⏳ The host extended the payment deadline',
      deposit: '💰 The host received your deposit',
      reminder: '⏰ Your booking will be released soon — the deposit is still due',
    },
    status: {
      pending: 'Status: waiting for the host',
      confirmed: 'Status: confirmed',
      checked_in: 'Status: checked in',
      checked_out: 'Status: checked out',
      cancelled: 'Status: cancelled',
      no_show: 'Status: no-show',
    },
    booking: (id: string) => `Booking ${id}`,
    times: (inTime: string, outTime: string) => `Check-in from ${inTime}, check-out by ${outTime}`,
    due: (x: string, until: string) => `Deposit ${x}${until ? ` — pay by ${until}` : ''}`,
    payTo: (recipient: string, details: string) => `Recipient: ${[recipient, details].filter(Boolean).join(' · ')}`,
    comment: (id: string) => `Transfer comment: ${id}`,
    open: 'Open booking',
    linkExpired: 'This link has expired. Open the booking in the app and tap “Follow in Telegram” again.',
  },
} satisfies Record<Lang, unknown>;

export function guestCopy(lang: string) {
  return GUEST[(lang in GUEST ? lang : 'ru') as Lang];
}
