// Telegram bot texts for hosts (ru / ky / en). Kyrgyz — draft for proofreading.

import type { Lang } from '../../../src/domain/types';

export const BOT = {
  ru: {
    welcome: 'Это бот Voyz Booking. Сюда приходят новые брони и оплаты — подтверждайте прямо из чата.',
    loginOk: 'Готово! Вернитесь в приложение Voyz — вход выполнен.',
    loginExpired: 'Код входа устарел. Нажмите «Войти через Telegram» в приложении ещё раз.',
    newBooking: 'Новая бронь',
    guestPaid: 'Гость сообщил об оплате — проверьте счёт',
    guestCancelled: 'Гость отменил бронь',
    holdExpired: 'Бронь снята: предоплата не пришла вовремя',
    icalConflict: 'Внимание: двойная продажа! Площадка заняла даты, на которые уже есть бронь',
    nights: (n: number) => `${n} ноч.`,
    guests: (n: number) => `${n} гост.`,
    total: 'Сумма',
    deposit: (x: string, until: string) => `Предоплата ${x}${until ? ` до ${until}` : ''}`,
    confirm: '✅ Подтвердить',
    decline: '✖️ Отклонить',
    received: '💰 Деньги пришли',
    open: 'Открыть в приложении',
    done: { confirmed: '✅ Подтверждена', cancelled: '✖️ Отклонена', deposit: '💰 Предоплата отмечена, бронь подтверждена' },
    notYours: 'Эта бронь не ваша или уже изменена',
    summary: (name: string) => `Доброе утро! «${name}» сегодня`,
    arrivals: 'Заезжают',
    departures: 'Выезжают',
    pending: (n: number) => `Ждут подтверждения: ${n}`,
    nothing: 'Заездов и выездов нет',
  },
  ky: {
    welcome: 'Бул Voyz Booking боту. Бул жерге жаңы брондоолор жана төлөмдөр келет — чаттан эле ырастаңыз.',
    loginOk: 'Даяр! Voyz тиркемесине кайтыңыз — кирүү аткарылды.',
    loginExpired: 'Кирүү коду эскирди. Тиркемеде «Telegram аркылуу кирүү» баскычын кайра басыңыз.',
    newBooking: 'Жаңы брондоо',
    guestPaid: 'Конок төлөдүм деп билдирди — эсепти текшериңиз',
    guestCancelled: 'Конок брондоону жокко чыгарды',
    holdExpired: 'Брондоо алынды: алдын ала төлөм убагында келген жок',
    icalConflict: 'Көңүл буруңуз: эки жолу сатуу! Аянтча брондоосу бар күндөрдү ээледи',
    nights: (n: number) => `${n} түн`,
    guests: (n: number) => `${n} конок`,
    total: 'Сумма',
    deposit: (x: string, until: string) => `Алдын ала төлөм ${x}${until ? `, ${until} чейин` : ''}`,
    confirm: '✅ Ырастоо',
    decline: '✖️ Баш тартуу',
    received: '💰 Акча келди',
    open: 'Тиркемеден ачуу',
    done: { confirmed: '✅ Ырасталды', cancelled: '✖️ Баш тартылды', deposit: '💰 Алдын ала төлөм белгиленди, брондоо ырасталды' },
    notYours: 'Бул брондоо сиздики эмес же өзгөртүлгөн',
    summary: (name: string) => `Кутман таң! «${name}» бүгүн`,
    arrivals: 'Келишет',
    departures: 'Кетишет',
    pending: (n: number) => `Ырастоону күтүүдө: ${n}`,
    nothing: 'Келүү жана кетүү жок',
  },
  en: {
    welcome: 'This is the Voyz Booking bot. New bookings and payments arrive here — confirm them right from the chat.',
    loginOk: 'Done! Go back to the Voyz app — you are signed in.',
    loginExpired: 'The sign-in code has expired. Tap “Sign in with Telegram” in the app again.',
    newBooking: 'New booking',
    guestPaid: 'The guest reported a payment — check your account',
    guestCancelled: 'The guest cancelled the booking',
    holdExpired: 'Booking released: the deposit did not arrive in time',
    icalConflict: 'Warning: double booking! An OTA blocked dates that already have a booking',
    nights: (n: number) => `${n} night${n === 1 ? '' : 's'}`,
    guests: (n: number) => `${n} guest${n === 1 ? '' : 's'}`,
    total: 'Total',
    deposit: (x: string, until: string) => `Deposit ${x}${until ? ` by ${until}` : ''}`,
    confirm: '✅ Confirm',
    decline: '✖️ Decline',
    received: '💰 Money received',
    open: 'Open in the app',
    done: { confirmed: '✅ Confirmed', cancelled: '✖️ Declined', deposit: '💰 Deposit recorded, booking confirmed' },
    notYours: 'This booking is not yours or has already changed',
    summary: (name: string) => `Good morning! “${name}” today`,
    arrivals: 'Arriving',
    departures: 'Leaving',
    pending: (n: number) => `Awaiting confirmation: ${n}`,
    nothing: 'No arrivals or departures',
  },
} satisfies Record<Lang, unknown>;

export function botCopy(lang: string) {
  return BOT[(lang in BOT ? lang : 'ru') as Lang];
}
